// Worker call + helpers for translating diagram data to Mermaid syntax.

import type { Architecture, GenerateResult, Selections } from './types';
import { LAYERS, VENDORS, INDUSTRIES } from './data';

const WORKER_URL =
  typeof window !== 'undefined' &&
  (window.location.hostname === 'localhost' ||
    window.location.hostname === '127.0.0.1')
    ? 'https://ea-explorer-worker.sfrancis2017.workers.dev'
    : 'https://ea-explorer-worker.sfrancis2017.workers.dev';

export interface GenerateError {
  error: string;
  retryAfter?: number;
}

export async function generateArchitectures(
  industryId: string,
  selections: Selections,
): Promise<GenerateResult> {
  const industry = INDUSTRIES.find((i) => i.id === industryId);
  if (!industry) throw new Error(`Unknown industry: ${industryId}`);

  // Resolve vendor IDs to {name, layerLabel} so the worker doesn't need
  // to know about the taxonomy.
  const resolved: Record<string, { name: string; layerLabel: string }[]> = {};
  for (const layer of LAYERS) {
    const ids = selections[layer.id] ?? [];
    if (ids.length === 0) continue;
    const pool = VENDORS[industryId]?.[layer.id] ?? [];
    resolved[layer.id] = ids
      .map((id) => pool.find((v) => v.id === id))
      .filter((v): v is { id: string; name: string; desc: string } => Boolean(v))
      .map((v) => ({ name: v.name, layerLabel: layer.label }));
  }

  const res = await fetch(`${WORKER_URL}/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      industryLabel: industry.label,
      selections: resolved,
    }),
  });

  if (!res.ok) {
    let message = `HTTP ${res.status}`;
    try {
      const err = (await res.json()) as GenerateError;
      message = err.error ?? message;
    } catch {
      /* ignore */
    }
    throw new Error(message);
  }

  return (await res.json()) as GenerateResult;
}

// Convert an Architecture to Mermaid syntax. Uses `graph TB` (top-to-bottom)
// with `subgraph` clusters per layer so the visual mirrors the layered EA
// taxonomy (Source → ERP → Middleware → Data → BI → AI). Edges show
// integration patterns. The same source is used for in-page rendering AND
// the "Copy as Mermaid" button.
// Open the given mermaid source in Mermaid Live Editor in a new tab.
// Uses the editor's `base64:` URL state format — UTF-8 safe encoding.
export function openInMermaidLive(arch: Architecture): void {
  const code = architectureToMermaid(arch);
  const state = {
    code,
    mermaid: '{\n  "theme": "default"\n}',
    autoSync: true,
    updateDiagram: true,
  };
  const utf8 = new TextEncoder().encode(JSON.stringify(state));
  let binary = '';
  for (let i = 0; i < utf8.length; i++) binary += String.fromCharCode(utf8[i]);
  const b64 = btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  const url = `https://mermaid.live/edit#base64:${b64}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

// All three architectures as a markdown document — each in its own
// `mermaid` fenced code block so it'll render as a real diagram in any
// markdown viewer (GitHub, Obsidian, Notion, VS Code preview, etc.).
export function architecturesToMarkdown(
  archs: Architecture[],
  industryLabel: string,
): string {
  const labels = ['Primary', 'Alternate 1', 'Alternate 2'];
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const sections = archs.map((arch, i) => {
    const code = architectureToMermaid(arch);
    return `## ${labels[i]}${arch.name ? ` — ${arch.name}` : ''}

\`\`\`mermaid
${code}
\`\`\`
`;
  });
  return `# ${industryLabel} reference architecture

_Generated by EA Architecture Explorer · sajivfrancis.com · ${date}_

${sections.join('\n')}`;
}

export function architectureToMermaid(arch: Architecture): string {
  const LAYER_ORDER = ['source', 'ot', 'erp', 'middleware', 'data', 'bi', 'ai'];
  const LAYER_LABELS: Record<string, string> = {
    source: 'Industry Input',
    ot: 'OT / Industrial',
    erp: 'ERP Platform',
    middleware: 'Integration',
    data: 'Data Platform',
    bi: 'Reporting & BI',
    ai: 'AI Layer',
  };

  // Group nodes by whatever `layer` value the model returns. Defensive:
  // the model sometimes invents synonyms (e.g. "Source", "datalayer") —
  // we don't want those nodes to silently disappear from the diagram, so
  // we render them under their reported layer name rather than dropping.
  const nodesByLayer: Record<string, typeof arch.nodes> = {};
  for (const n of arch.nodes ?? []) {
    const key = (n.layer ?? '_unknown').toLowerCase();
    if (!nodesByLayer[key]) nodesByLayer[key] = [];
    nodesByLayer[key]!.push(n);
  }

  const safeId = (id: string) => id.replace(/[^a-zA-Z0-9]/g, '_');
  const safeText = (s: string) => (s ?? '').replace(/"/g, "'");

  const lines: string[] = ['graph TB'];

  // Render canonical layers first (in fixed order), then any extras the
  // model returned that don't match our taxonomy.
  const canonical = LAYER_ORDER.filter((l) => nodesByLayer[l]?.length);
  const extras = Object.keys(nodesByLayer).filter(
    (l) => !LAYER_ORDER.includes(l) && nodesByLayer[l]?.length,
  );
  const orderedLayers = [...canonical, ...extras];

  for (const layerKey of orderedLayers) {
    const nodes = nodesByLayer[layerKey]!;
    const label = LAYER_LABELS[layerKey] ?? layerKey;
    lines.push(`  subgraph ${safeId(layerKey)}["${label}"]`);
    for (const node of nodes) {
      lines.push(`    ${safeId(node.id)}["${safeText(node.vendor)}"]`);
    }
    lines.push('  end');
  }

  // Last-resort fallback: if for some reason no nodes came through but
  // edges did, emit standalone node defs from edge endpoints so we at
  // least have *something* labelled. (Cheap insurance against malformed
  // model output.)
  if (orderedLayers.length === 0 && (arch.edges ?? []).length > 0) {
    const seen = new Set<string>();
    for (const edge of arch.edges) {
      for (const id of [edge.from, edge.to]) {
        if (seen.has(id)) continue;
        seen.add(id);
        lines.push(`  ${safeId(id)}["${safeText(id)}"]`);
      }
    }
  }

  for (const edge of arch.edges ?? []) {
    const fromId = safeId(edge.from);
    const toId = safeId(edge.to);
    const label = safeText(edge.label);
    lines.push(label ? `  ${fromId} -->|${label}| ${toId}` : `  ${fromId} --> ${toId}`);
  }

  return lines.join('\n');
}
