// Taxonomy: industries, architecture layers, and per-industry vendors.
// Sourced from the original JSX4EA brief; vendor lists are intentionally
// curated (not exhaustive) to keep selections legible.

import type { Industry, Layer, VendorMap } from './types';

// Industry taxonomy mirrors scripts/sic_map.json (the SEC-corpus source of
// truth): same ids + representative SIC codes. `examples` are representative
// public filers in each SIC bucket — they ground the picker in real EDGAR
// membership (not a claim about which systems any one company runs).
export const INDUSTRIES: Industry[] = [
  { id: 'oil_gas',           label: 'Oil & Gas',                  icon: '⛽', desc: 'Upstream, midstream & downstream',        accent: '#c2741f', sic: ['1311', '1381', '2911', '4922', '4924'], examples: ['ExxonMobil', 'Chevron', 'ConocoPhillips', 'Schlumberger'] },
  { id: 'financial',         label: 'Financial Services',         icon: '🏦', desc: 'Banking, capital markets & insurance',    accent: '#3b82f6', sic: ['6021', '6022', '6199', '6211', '6311'], examples: ['JPMorgan Chase', 'Bank of America', 'Goldman Sachs', 'BlackRock'] },
  { id: 'manufacturing',     label: 'Manufacturing',              icon: '🏭', desc: 'Discrete & process manufacturing',        accent: '#10b981', sic: ['3711', '3559', '3312', '2821', '3724'], examples: ['Boeing', 'Ford', 'General Motors', 'Caterpillar'] },
  { id: 'healthcare',        label: 'Healthcare',                 icon: '🏥', desc: 'Providers, payers & life sciences',       accent: '#dc2626', sic: ['2834', '2836', '3841', '3845', '8060'], examples: ['Pfizer', 'Johnson & Johnson', 'UnitedHealth', 'Medtronic'] },
  { id: 'retail_cpg',        label: 'Retail / CPG',               icon: '🛒', desc: 'Retail, e-commerce & consumer goods',     accent: '#7c3aed', sic: ['5311', '5411', '5961', '2000', '2080'], examples: ['Walmart', 'Costco', 'Procter & Gamble', 'PepsiCo'] },
  { id: 'utilities',         label: 'Utilities',                  icon: '⚡', desc: 'Power, gas & water utilities',            accent: '#0891b2', sic: ['4911', '4924', '4931', '4941'],         examples: ['NextEra Energy', 'Duke Energy', 'Southern Company', 'Dominion'] },
  { id: 'semiconductors',    label: 'Semiconductors',             icon: '🔬', desc: 'Chip design, fabrication & equipment',    accent: '#0ea5e9', sic: ['3674', '3559', '3827'],                 examples: ['NVIDIA', 'AMD', 'Broadcom', 'Qualcomm', 'Micron'] },
  { id: 'software_internet', label: 'Software & Internet',        icon: '💻', desc: 'SaaS, cloud & internet platforms',        accent: '#6366f1', sic: ['7372', '7371', '7373', '7374', '7370'], examples: ['Microsoft', 'Salesforce', 'Oracle', 'ServiceNow', 'Adobe'] },
  { id: 'hardware_comms',    label: 'Hardware & Communications',  icon: '📡', desc: 'Devices, networking & telecom gear',      accent: '#14b8a6', sic: ['3571', '3576', '3577', '3661', '3663'], examples: ['Cisco', 'Dell', 'HPE', 'Arista', 'Motorola Solutions'] },
];

export const LAYERS: Layer[] = [
  { id: 'source',     label: 'Industry Input Systems',   sublabel: 'Operational source of truth',           icon: '📥', accent: '#6b7280' },
  { id: 'ot',         label: 'OT / Industrial Systems',  sublabel: 'Plant floor & field data',              icon: '🏗️', accent: '#c2741f', onlyFor: ['oil_gas', 'manufacturing', 'utilities', 'semiconductors'] },
  { id: 'erp',        label: 'ERP Platform',             sublabel: 'Core business system of record',        icon: '🏢', accent: '#0891b2' },
  { id: 'middleware', label: 'Integration / Middleware', sublabel: 'API management & event streaming',     icon: '🔗', accent: '#7c3aed' },
  { id: 'data',       label: 'Data Platform',            sublabel: 'Warehouse, lakehouse & data fabric',   icon: '🗄️', accent: '#047857' },
  { id: 'bi',         label: 'Reporting & BI',           sublabel: 'Analytics & visualization layer',      icon: '📊', accent: '#be185d' },
  { id: 'ai',         label: 'AI Integration Layer',     sublabel: 'Intelligence, automation & LLMs',      icon: '🤖', accent: '#b45309' },
];

export const VENDORS: VendorMap = {
  oil_gas: {
    source: [
      { id: 'quorum',    name: 'Quorum Business Solutions', desc: 'O&G production accounting' },
      { id: 'wellview',  name: 'WellView (Peloton)',         desc: 'Well data management' },
      { id: 'petrel',    name: 'Schlumberger Petrel',        desc: 'Geological modelling' },
      { id: 'landmark',  name: 'Halliburton Landmark',       desc: 'Reservoir engineering' },
      { id: 'p2energy',  name: 'P2 Energy Solutions',        desc: 'Revenue & royalty accounting' },
      { id: 'aspentech', name: 'AspenTech (aspenONE)',       desc: 'Process optimization & engineering' },
    ],
    ot: [
      { id: 'pi_system', name: 'AVEVA PI System',         desc: 'Real-time sensor historian' },
      { id: 'honeywell', name: 'Honeywell Experion PKS',  desc: 'Process control & DCS' },
      { id: 'emerson',   name: 'Emerson DeltaV',          desc: 'Process automation' },
      { id: 'abb',       name: 'ABB Ability',             desc: 'Industrial IoT platform' },
      { id: 'ge_proficy',name: 'GE Digital Proficy',      desc: 'Plant operations suite' },
    ],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',             desc: 'Industry-leading ERP' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',     desc: 'Cloud ERP suite' },
      { id: 'ifs',       name: 'IFS Cloud',               desc: 'Asset & maintenance focus' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',  desc: 'Cloud ERP + CRM' },
      { id: 'infor_ln',  name: 'Infor M3 / LN',           desc: 'Process industry ERP' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'API-led connectivity' },
      { id: 'sap_is',    name: 'SAP Integration Suite',      desc: 'SAP-native integration' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Logic Apps + Service Bus' },
      { id: 'ibm_app',   name: 'IBM App Connect',            desc: 'Enterprise integration' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Event streaming platform' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',              desc: 'Cloud data warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse',   desc: 'Unified analytics platform' },
      { id: 'sap_ds',    name: 'SAP Datasphere',         desc: 'SAP-native data fabric' },
      { id: 'fabric',    name: 'Microsoft Fabric',       desc: 'Unified analytics SaaS' },
      { id: 'teradata',  name: 'Teradata Vantage',       desc: 'Enterprise analytics' },
    ],
    bi: [
      { id: 'sac',       name: 'SAP Analytics Cloud',    desc: 'Planning + BI unified' },
      { id: 'powerbi',   name: 'Microsoft Power BI',     desc: 'Self-service analytics' },
      { id: 'tableau',   name: 'Tableau (Salesforce)',   desc: 'Visual analytics' },
      { id: 'qlik',      name: 'Qlik Sense',             desc: 'Associative analytics' },
      { id: 'spotfire',  name: 'TIBCO Spotfire',         desc: 'O&G analytics specialist' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI / Copilot Studio', desc: 'Microsoft AI ecosystem' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',               desc: 'Foundation model platform' },
      { id: 'claude_api', name: 'Anthropic Claude API',      desc: 'Enterprise-grade LLM' },
      { id: 'c3ai',       name: 'C3.ai',                     desc: 'Industrial AI applications' },
      { id: 'palantir',   name: 'Palantir AIP',              desc: 'Operational AI for O&G' },
    ],
  },
  financial: {
    source: [
      { id: 'temenos',   name: 'Temenos Transact',  desc: 'Core banking platform' },
      { id: 'finastra',  name: 'Finastra Fusion',   desc: 'Banking & capital markets' },
      { id: 'murex',     name: 'Murex MX.3',        desc: 'Trading & risk management' },
      { id: 'bloomberg', name: 'Bloomberg B-PIPE',  desc: 'Market data feed' },
      { id: 'simcorp',   name: 'SimCorp Dimension', desc: 'Investment management' },
      { id: 'fis',       name: 'FIS Modern Banking',desc: 'Core banking & payments' },
      { id: 'aladdin',   name: 'BlackRock Aladdin', desc: 'Investment & risk platform' },
    ],
    ot: [],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',             desc: 'Finance & risk ERP' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',     desc: 'Financial management' },
      { id: 'workday',   name: 'Workday Financial Mgmt',  desc: 'Cloud-native finance' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',  desc: 'Finance & operations' },
      { id: 'sap_fcc',   name: 'SAP Central Finance',     desc: 'Finance consolidation hub' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'API-led connectivity' },
      { id: 'ibm_app',   name: 'IBM App Connect',            desc: 'FS-grade integration' },
      { id: 'tibco',     name: 'TIBCO BusinessWorks',        desc: 'Capital markets messaging' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Real-time event streams' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Cloud integration' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Cloud data warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'Unified analytics' },
      { id: 'teradata',  name: 'Teradata Vantage',     desc: 'Risk analytics workloads' },
      { id: 'fabric',    name: 'Microsoft Fabric',     desc: 'Unified analytics SaaS' },
      { id: 'bigquery',  name: 'Google BigQuery',      desc: 'Serverless warehouse' },
    ],
    bi: [
      { id: 'powerbi',   name: 'Microsoft Power BI',      desc: 'Financial dashboards' },
      { id: 'tableau',   name: 'Tableau',                 desc: 'Risk & performance viz' },
      { id: 'qlik',      name: 'Qlik Sense',              desc: 'Regulatory reporting' },
      { id: 'oracle_ac', name: 'Oracle Analytics Cloud',  desc: 'Integrated FS analytics' },
      { id: 'mstr',      name: 'MicroStrategy',           desc: 'Enterprise BI' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI / Copilot',     desc: 'Microsoft AI platform' },
      { id: 'claude_api', name: 'Anthropic Claude API',   desc: 'Document & analysis AI' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',            desc: 'Foundation models' },
      { id: 'ibm_wx',     name: 'IBM watsonx',            desc: 'Trusted AI for FS' },
      { id: 'datarobot',  name: 'DataRobot',              desc: 'Risk model automation' },
      { id: 'sas',        name: 'SAS Viya',               desc: 'Risk, fraud & analytics' },
      { id: 'fico',       name: 'FICO Platform',          desc: 'Fraud & decisioning' },
    ],
  },
  manufacturing: {
    source: [
      { id: 'ptc_wc',    name: 'PTC Windchill',     desc: 'PLM & product data' },
      { id: 'siemens_tc',name: 'Siemens Teamcenter',desc: 'Product lifecycle mgmt' },
      { id: 'dassault',  name: 'Dassault ENOVIA',   desc: '3D PLM platform' },
      { id: 'arena_plm', name: 'Arena PLM',         desc: 'Cloud PLM for electronics' },
      { id: 'opcenter',  name: 'Siemens Opcenter',  desc: 'Manufacturing execution' },
    ],
    ot: [
      { id: 'siemens_s', name: 'Siemens SIMATIC',      desc: 'PLC & SCADA platform' },
      { id: 'rockwell',  name: 'Rockwell FactoryTalk', desc: 'Production intelligence' },
      { id: 'aveva_ww',  name: 'AVEVA Wonderware',     desc: 'Industrial operations' },
      { id: 'ge_proficy',name: 'GE Digital Proficy',   desc: 'MES & plant operations' },
      { id: 'kepware',   name: 'PTC Kepware',          desc: 'Industrial connectivity' },
      { id: 'thingworx', name: 'PTC ThingWorx',        desc: 'Industrial IoT platform' },
    ],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',                desc: 'Discrete & process mfg' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',        desc: 'Manufacturing cloud' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',     desc: 'SME manufacturing' },
      { id: 'infor_csi', name: 'Infor CloudSuite Industrial',desc: 'Complex manufacturing' },
      { id: 'epicor',    name: 'Epicor Kinetic',             desc: 'Job shop manufacturing' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'IT/OT convergence' },
      { id: 'sap_is',    name: 'SAP Integration Suite',      desc: 'SAP-native flows' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Cloud + edge' },
      { id: 'boomi',     name: 'Boomi (Dell)',               desc: 'Low-code integration' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Shop floor event streams' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Enterprise warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'IoT + analytics' },
      { id: 'fabric',    name: 'Microsoft Fabric',     desc: 'Azure-native analytics' },
      { id: 'sap_ds',    name: 'SAP Datasphere',       desc: 'SAP data fabric' },
      { id: 'aws_rs',    name: 'AWS Redshift',         desc: 'Columnar analytics' },
    ],
    bi: [
      { id: 'powerbi',    name: 'Power BI',             desc: 'Production dashboards' },
      { id: 'sac',        name: 'SAP Analytics Cloud',  desc: 'Integrated planning' },
      { id: 'tableau',    name: 'Tableau',              desc: 'Supply chain viz' },
      { id: 'qlik',       name: 'Qlik Sense',           desc: 'OEE & quality analytics' },
      { id: 'thoughtspot',name: 'ThoughtSpot',          desc: 'Search-driven analytics' },
    ],
    ai: [
      { id: 'azure_ai',     name: 'Azure AI / Copilot', desc: 'Predictive maintenance' },
      { id: 'aws_bedrock',  name: 'AWS Bedrock',        desc: 'Manufacturing AI' },
      { id: 'databricks_ai',name: 'Databricks AI',      desc: 'Quality ML pipelines' },
      { id: 'c3ai',         name: 'C3.ai',              desc: 'Supply chain AI' },
      { id: 'sap_ai',       name: 'SAP AI Core',        desc: 'Embedded AI in SAP' },
    ],
  },
  healthcare: {
    source: [
      { id: 'epic',     name: 'Epic Systems',     desc: 'Electronic health records' },
      { id: 'cerner',   name: 'Oracle Cerner',    desc: 'Clinical data platform' },
      { id: 'meditech', name: 'Meditech Expanse', desc: 'Community hospital EHR' },
      { id: 'veeva',    name: 'Veeva Vault',      desc: 'Life sciences content' },
      { id: 'hl7_fhir', name: 'HL7 FHIR Sources', desc: 'Interoperability feeds' },
      { id: 'athena',   name: 'athenahealth',     desc: 'Ambulatory EHR & RCM' },
    ],
    ot: [],
    erp: [
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',          desc: 'Healthcare finance' },
      { id: 'sap_s4',    name: 'SAP S/4HANA',                  desc: 'Large health system ERP' },
      { id: 'workday',   name: 'Workday',                      desc: 'HR & finance cloud' },
      { id: 'infor_hc',  name: 'Infor CloudSuite Healthcare',  desc: 'Healthcare-specific ERP' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',       desc: 'Mid-market healthcare' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',           desc: 'HL7/FHIR integration' },
      { id: 'azure_hds', name: 'Azure Health Data Services',  desc: 'FHIR-native cloud' },
      { id: 'ibm_app',   name: 'IBM App Connect',             desc: 'Clinical data exchange' },
      { id: 'rhapsody',  name: 'Rhapsody Integration Engine', desc: 'Healthcare interop' },
      { id: 'boomi',     name: 'Boomi',                       desc: 'EDI & HL7 workflows' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',                desc: 'HIPAA-compliant warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse',     desc: 'Clinical analytics' },
      { id: 'fabric',    name: 'Microsoft Fabric',         desc: 'Azure health analytics' },
      { id: 'aws_hl',    name: 'AWS HealthLake',           desc: 'FHIR datastore' },
      { id: 'oracle_hdi',name: 'Oracle Health Data Intel', desc: 'Clinical intelligence' },
      { id: 'health_cat',name: 'Health Catalyst',          desc: 'Healthcare data & analytics' },
    ],
    bi: [
      { id: 'powerbi',    name: 'Power BI',               desc: 'Clinical ops dashboards' },
      { id: 'tableau',    name: 'Tableau',                desc: 'Population health analytics' },
      { id: 'qlik',       name: 'Qlik Sense',             desc: 'Revenue cycle analytics' },
      { id: 'thoughtspot',name: 'ThoughtSpot',            desc: 'Self-service clinical BI' },
      { id: 'oracle_ac',  name: 'Oracle Analytics Cloud', desc: 'Integrated health BI' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI Health Bot',      desc: 'Clinical decision support' },
      { id: 'aws_bedrock',name: 'AWS Bedrock + HealthLake', desc: 'Clinical NLP' },
      { id: 'claude_api', name: 'Anthropic Claude API',     desc: 'Medical documentation AI' },
      { id: 'google_v',   name: 'Google Vertex AI',         desc: 'Med-PaLM integration' },
      { id: 'ibm_wx',     name: 'IBM watsonx',              desc: 'Trusted healthcare AI' },
      { id: 'nuance_dax', name: 'Nuance DAX (Microsoft)',   desc: 'Ambient clinical documentation' },
    ],
  },
  retail_cpg: {
    source: [
      { id: 'manhattan', name: 'Manhattan Associates WMS', desc: 'Warehouse management' },
      { id: 'blueyonder',name: 'Blue Yonder',              desc: 'Supply chain planning' },
      { id: 'relex',     name: 'RELEX Solutions',          desc: 'Demand forecasting' },
      { id: 'o9',        name: 'o9 Solutions',             desc: 'Integrated business planning' },
      { id: 'sf_cc',     name: 'Salesforce Commerce Cloud',desc: 'Omnichannel commerce' },
      { id: 'sap_car',   name: 'SAP Customer Activity Repo',desc: 'Omnichannel POS & demand data' },
    ],
    ot: [],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',                  desc: 'Retail & CPG ERP' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',          desc: 'Retail cloud ERP' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',       desc: 'Retail operations' },
      { id: 'infor_d',   name: 'Infor CloudSuite Distribution',desc: 'Distribution ERP' },
      { id: 'netsuite',  name: 'Oracle NetSuite',              desc: 'Mid-market retail ERP' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'Retail API platform' },
      { id: 'boomi',     name: 'Boomi',                      desc: 'EDI & supplier connect' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Cloud-native flows' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Real-time inventory events' },
      { id: 'tibco',     name: 'TIBCO',                      desc: 'Supply chain messaging' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',         desc: 'Retail analytics warehouse' },
      { id: 'databricks',name: 'Databricks',        desc: 'Customer data platform' },
      { id: 'bigquery',  name: 'Google BigQuery',   desc: 'Marketing analytics' },
      { id: 'fabric',    name: 'Microsoft Fabric',  desc: 'Retail intelligence' },
      { id: 'aws_rs',    name: 'AWS Redshift',      desc: 'E-commerce analytics' },
    ],
    bi: [
      { id: 'powerbi',    name: 'Power BI',         desc: 'Sales & inventory BI' },
      { id: 'tableau',    name: 'Tableau',          desc: 'Category management' },
      { id: 'looker',     name: 'Looker (Google)',  desc: 'Embedded retail analytics' },
      { id: 'qlik',       name: 'Qlik Sense',       desc: 'Omnichannel analytics' },
      { id: 'thoughtspot',name: 'ThoughtSpot',      desc: 'AI-driven retail insights' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI / Copilot',   desc: 'Retail personalization' },
      { id: 'google_v',   name: 'Google Vertex AI',     desc: 'Recommendations AI' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',          desc: 'Generative AI for retail' },
      { id: 'claude_api', name: 'Anthropic Claude API', desc: 'Product content AI' },
      { id: 'c3ai',       name: 'C3.ai',                desc: 'Demand forecasting AI' },
      { id: 'dyield',     name: 'Dynamic Yield',        desc: 'Personalization & recommendations' },
    ],
  },
  utilities: {
    source: [
      { id: 'itron',    name: 'Itron Smart Grid', desc: 'AMI & meter data mgmt' },
      { id: 'oracle_u', name: 'Oracle Utilities', desc: 'CIS & billing system' },
      { id: 'esri',     name: 'Esri ArcGIS',      desc: 'Geospatial asset registry' },
      { id: 'trimble',  name: 'Trimble Unity',    desc: 'Network management' },
      { id: 'landis',   name: 'Landis+Gyr',       desc: 'Smart metering platform' },
    ],
    ot: [
      { id: 'aveva_ww', name: 'AVEVA Wonderware',         desc: 'Grid SCADA platform' },
      { id: 'ge_adms',  name: 'GE Grid Solutions (ADMS)', desc: 'Distribution management' },
      { id: 'abb_sc',   name: 'ABB Ability SCADA',        desc: 'Substation automation' },
      { id: 'siemens_eg',name: 'Siemens Energy Grid',     desc: 'Smart grid operations' },
      { id: 'pi_system',name: 'AVEVA PI System',          desc: 'Real-time historian' },
      { id: 'schneider',name: 'Schneider EcoStruxure',    desc: 'ADMS & grid automation' },
    ],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',             desc: 'Utilities IS-U / BRIM' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',     desc: 'Asset & finance mgmt' },
      { id: 'ifs',       name: 'IFS Cloud',               desc: 'Asset lifecycle mgmt' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365',  desc: 'Field service + finance' },
      { id: 'maximo',    name: 'IBM Maximo APM',          desc: 'Asset performance mgmt' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'IT/OT integration hub' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Cloud + edge hybrid' },
      { id: 'ibm_app',   name: 'IBM App Connect',            desc: 'Utility data exchange' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Grid event streaming' },
      { id: 'sap_is',    name: 'SAP Integration Suite',      desc: 'SAP-native flows' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Enterprise warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'Grid analytics + IoT' },
      { id: 'fabric',    name: 'Microsoft Fabric',     desc: 'Azure-native analytics' },
      { id: 'sap_ds',    name: 'SAP Datasphere',       desc: 'SAP data fabric' },
      { id: 'aws_rs',    name: 'AWS Redshift',         desc: 'Smart grid data lake' },
    ],
    bi: [
      { id: 'powerbi',  name: 'Power BI',                desc: 'Grid operations BI' },
      { id: 'sac',      name: 'SAP Analytics Cloud',     desc: 'Utilities planning' },
      { id: 'tableau',  name: 'Tableau',                 desc: 'Asset performance dashboards' },
      { id: 'esri_ins', name: 'Esri ArcGIS Insights',    desc: 'Spatial analytics' },
      { id: 'qlik',     name: 'Qlik Sense',              desc: 'Outage & risk analytics' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI / IoT Hub',  desc: 'Grid anomaly detection' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',         desc: 'Predictive maintenance AI' },
      { id: 'c3ai',       name: 'C3.ai',               desc: 'Energy demand forecasting' },
      { id: 'palantir',   name: 'Palantir AIP',        desc: 'Grid operations AI' },
      { id: 'sap_ai',     name: 'SAP AI Core',         desc: 'Embedded AI in SAP' },
    ],
  },

  semiconductors: {
    source: [
      { id: 'cadence',    name: 'Cadence',               desc: 'EDA design & verification' },
      { id: 'synopsys',   name: 'Synopsys',              desc: 'EDA, IP & design tools' },
      { id: 'siemens_eda',name: 'Siemens EDA (Calibre)', desc: 'Physical verification & signoff' },
      { id: 'teamcenter', name: 'Siemens Teamcenter',    desc: 'PLM for chip & package' },
      { id: 'ansys',      name: 'Ansys',                 desc: 'Multiphysics & reliability sim' },
    ],
    ot: [
      { id: 'opcenter_cs',name: 'Siemens Opcenter (Camstar)', desc: 'Semiconductor MES' },
      { id: 'applied_sf', name: 'Applied SmartFactory',       desc: 'Fab automation & scheduling' },
      { id: 'criticalmfg',name: 'Critical Manufacturing MES', desc: 'Modern fab MES' },
      { id: 'peer_group', name: 'PEER Group FactoryWorks',    desc: 'Equipment integration (SECS/GEM)' },
      { id: 'pi_system',  name: 'AVEVA PI System',            desc: 'Fab equipment historian' },
    ],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',            desc: 'Dominant ERP in semis' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',    desc: 'Cloud ERP suite' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365', desc: 'Cloud ERP + CRM' },
      { id: 'kinaxis',   name: 'Kinaxis RapidResponse',  desc: 'Supply-chain planning' },
      { id: 'sap_ibp',   name: 'SAP IBP',                desc: 'Integrated demand/supply planning' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',          desc: 'API-led connectivity' },
      { id: 'sap_is',    name: 'SAP Integration Suite',      desc: 'SAP-native integration' },
      { id: 'confluent', name: 'Confluent (Kafka)',          desc: 'Fab event streaming' },
      { id: 'azure_is',  name: 'Azure Integration Services', desc: 'Logic Apps + Service Bus' },
      { id: 'boomi',     name: 'Boomi',                      desc: 'Cloud integration platform' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Cloud data warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'Yield & test analytics at scale' },
      { id: 'bigquery',  name: 'Google BigQuery',      desc: 'Serverless analytics' },
      { id: 'fabric',    name: 'Microsoft Fabric',     desc: 'Unified analytics SaaS' },
      { id: 'aws_rs',    name: 'AWS Redshift',         desc: 'Cloud data lake' },
    ],
    bi: [
      { id: 'pdf_exensio',name: 'PDF Solutions Exensio', desc: 'Semiconductor yield analytics' },
      { id: 'spotfire',   name: 'TIBCO Spotfire',        desc: 'Engineering & yield analysis' },
      { id: 'powerbi',    name: 'Microsoft Power BI',    desc: 'Self-service analytics' },
      { id: 'tableau',    name: 'Tableau (Salesforce)',  desc: 'Visual analytics' },
      { id: 'sac',        name: 'SAP Analytics Cloud',   desc: 'Planning + BI unified' },
    ],
    ai: [
      { id: 'nvidia_ai',  name: 'NVIDIA AI Enterprise', desc: 'GPU AI/ML platform' },
      { id: 'azure_ai',   name: 'Azure AI / OpenAI',    desc: 'Microsoft AI ecosystem' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',          desc: 'Foundation model platform' },
      { id: 'claude_api', name: 'Anthropic Claude API', desc: 'Enterprise-grade LLM' },
      { id: 'vertex_ai',  name: 'Google Vertex AI',     desc: 'Managed ML platform' },
    ],
  },

  software_internet: {
    source: [
      { id: 'salesforce', name: 'Salesforce',        desc: 'CRM system of record' },
      { id: 'hubspot',    name: 'HubSpot',           desc: 'CRM & marketing platform' },
      { id: 'stripe',     name: 'Stripe Billing',    desc: 'Payments & revenue' },
      { id: 'zuora',      name: 'Zuora',             desc: 'Subscription billing' },
      { id: 'amplitude',  name: 'Amplitude',         desc: 'Product usage analytics' },
    ],
    ot: [],
    erp: [
      { id: 'netsuite',  name: 'Oracle NetSuite',        desc: 'Dominant cloud ERP for SaaS' },
      { id: 'workday',   name: 'Workday',                desc: 'Cloud finance & HCM' },
      { id: 'sap_s4',    name: 'SAP S/4HANA',            desc: 'Enterprise ERP at scale' },
      { id: 'intacct',   name: 'Sage Intacct',           desc: 'Mid-market finance' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365', desc: 'Cloud ERP + CRM' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint', desc: 'API-led connectivity' },
      { id: 'workato',   name: 'Workato',           desc: 'SaaS automation & iPaaS' },
      { id: 'boomi',     name: 'Boomi',             desc: 'Cloud integration platform' },
      { id: 'confluent', name: 'Confluent (Kafka)', desc: 'Event streaming backbone' },
      { id: 'kong',      name: 'Kong',              desc: 'API gateway & service mesh' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Cloud data warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'Unified analytics + ML' },
      { id: 'bigquery',  name: 'Google BigQuery',      desc: 'Serverless analytics' },
      { id: 'fivetran',  name: 'Fivetran + dbt',       desc: 'ELT pipelines & transforms' },
      { id: 'aws_rs',    name: 'AWS Redshift',         desc: 'Cloud data lake' },
    ],
    bi: [
      { id: 'looker',    name: 'Looker (Google)',  desc: 'Modeled BI for product data' },
      { id: 'tableau',   name: 'Tableau',          desc: 'Visual analytics' },
      { id: 'powerbi',   name: 'Microsoft Power BI',desc: 'Self-service analytics' },
      { id: 'sigma',     name: 'Sigma Computing',  desc: 'Cloud spreadsheet BI' },
      { id: 'thoughtspot',name: 'ThoughtSpot',     desc: 'Search & AI analytics' },
    ],
    ai: [
      { id: 'openai',     name: 'OpenAI API',           desc: 'GPT model platform' },
      { id: 'claude_api', name: 'Anthropic Claude API', desc: 'Enterprise-grade LLM' },
      { id: 'azure_ai',   name: 'Azure OpenAI',         desc: 'Governed OpenAI on Azure' },
      { id: 'vertex_ai',  name: 'Google Vertex AI',     desc: 'Managed ML platform' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',          desc: 'Foundation model platform' },
    ],
  },

  hardware_comms: {
    source: [
      { id: 'teamcenter', name: 'Siemens Teamcenter', desc: 'PLM system of record' },
      { id: 'windchill',  name: 'PTC Windchill',      desc: 'Product lifecycle management' },
      { id: 'agile_plm',  name: 'Oracle Agile PLM',   desc: 'Hi-tech PLM & change control' },
      { id: 'arena',      name: 'Arena PLM',          desc: 'Cloud-native PLM/QMS' },
      { id: 'sap_plm',    name: 'SAP PLM',            desc: 'SAP-native product lifecycle' },
    ],
    ot: [],
    erp: [
      { id: 'sap_s4',    name: 'SAP S/4HANA',            desc: 'Hi-tech & supply-chain ERP' },
      { id: 'oracle_fc', name: 'Oracle Fusion Cloud',    desc: 'Cloud ERP suite' },
      { id: 'ms_d365',   name: 'Microsoft Dynamics 365', desc: 'Cloud ERP + CRM' },
      { id: 'infor_ln',  name: 'Infor CloudSuite',       desc: 'Industrial / hi-tech ERP' },
      { id: 'kinaxis',   name: 'Kinaxis RapidResponse',  desc: 'Supply-chain planning' },
    ],
    middleware: [
      { id: 'mulesoft',  name: 'MuleSoft Anypoint',     desc: 'API-led connectivity' },
      { id: 'sap_is',    name: 'SAP Integration Suite',  desc: 'SAP-native integration' },
      { id: 'boomi',     name: 'Boomi',                  desc: 'Cloud integration platform' },
      { id: 'confluent', name: 'Confluent (Kafka)',      desc: 'Telemetry event streaming' },
      { id: 'ibm_app',   name: 'IBM App Connect',        desc: 'Enterprise integration' },
    ],
    data: [
      { id: 'snowflake', name: 'Snowflake',            desc: 'Cloud data warehouse' },
      { id: 'databricks',name: 'Databricks Lakehouse', desc: 'Device telemetry analytics' },
      { id: 'fabric',    name: 'Microsoft Fabric',     desc: 'Unified analytics SaaS' },
      { id: 'bigquery',  name: 'Google BigQuery',      desc: 'Serverless analytics' },
      { id: 'aws_rs',    name: 'AWS Redshift',         desc: 'Cloud data lake' },
    ],
    bi: [
      { id: 'powerbi',   name: 'Microsoft Power BI',   desc: 'Self-service analytics' },
      { id: 'tableau',   name: 'Tableau (Salesforce)', desc: 'Visual analytics' },
      { id: 'sac',       name: 'SAP Analytics Cloud',  desc: 'Planning + BI unified' },
      { id: 'qlik',      name: 'Qlik Sense',           desc: 'Associative analytics' },
      { id: 'thoughtspot',name: 'ThoughtSpot',         desc: 'Search & AI analytics' },
    ],
    ai: [
      { id: 'azure_ai',   name: 'Azure AI / OpenAI',    desc: 'Microsoft AI ecosystem' },
      { id: 'aws_bedrock',name: 'AWS Bedrock',          desc: 'Foundation model platform' },
      { id: 'claude_api', name: 'Anthropic Claude API', desc: 'Enterprise-grade LLM' },
      { id: 'vertex_ai',  name: 'Google Vertex AI',     desc: 'Managed ML platform' },
      { id: 'nvidia_ai',  name: 'NVIDIA AI Enterprise', desc: 'Edge & device AI' },
    ],
  },
};

export function getApplicableLayers(industryId: string): Layer[] {
  return LAYERS.filter((l) => !l.onlyFor || l.onlyFor.includes(industryId));
}
