import { useEffect, useRef, useState } from 'react';
import type { Architecture, Industry, GenerateResult } from './types';
import {
  architectureToMermaid,
  architecturesToMarkdown,
  openInMermaidLive,
} from './api';

const TAB_LABELS = ['Primary', 'Alternate 1', 'Alternate 2'];

interface Props {
  result: GenerateResult;
  industry: Industry;
  onReset: () => void;
}

export function ResultsView({ result, industry, onReset }: Props) {
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied] = useState<number | null>(null);

  if (!result?.architectures?.length) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <p style={{ color: 'var(--color-fg-muted)' }}>
          The response couldn't be parsed. This is rare — try regenerating.
        </p>
        <button type="button" onClick={onReset} className="ea-action">
          Start over
        </button>
      </div>
    );
  }

  const archs = result.architectures;
  const current = archs[activeTab];

  async function copyAllAsMarkdown() {
    const md = architecturesToMarkdown(archs, industry.label);
    try {
      await navigator.clipboard.writeText(md);
      setCopied(-1); // -1 = "all" copied
      setTimeout(() => setCopied(null), 1800);
    } catch {
      window.prompt('Copy this markdown:', md);
    }
  }

  return (
    <div>
      <div className="ea-industry-banner">
        <span className="ea-industry-banner-icon" aria-hidden="true">
          {industry.icon}
        </span>
        <div style={{ flex: 1 }}>
          <div className="ea-industry-banner-title">
            {industry.label} reference architecture
          </div>
          <div className="ea-industry-banner-sub">
            Three options below — primary plus two alternates. Switch tabs on
            screen, or print/save the page to capture all three as a PDF.
          </div>
        </div>
        <button type="button" onClick={onReset} className="ea-action">
          ← New session
        </button>
      </div>

      {/* On-screen tabs (hidden in print) */}
      <div className="ea-results-tabs" role="tablist">
        {archs.map((arch, i) => (
          <button
            key={i}
            type="button"
            role="tab"
            aria-selected={activeTab === i}
            onClick={() => setActiveTab(i)}
            className={`ea-results-tab${activeTab === i ? ' active' : ''}`}
          >
            {TAB_LABELS[i]}
            {arch.name && (
              <span className="ea-results-tab-name">{arch.name}</span>
            )}
          </button>
        ))}
      </div>

      {/* On-screen: render only the active tab */}
      <div className="ea-screen-only">
        <ArchitectureSection arch={current} index={activeTab} />
      </div>

      {/* Print-only: render ALL three architectures with page breaks */}
      <div className="ea-print-only">
        {archs.map((arch, i) => (
          <ArchitectureSection key={i} arch={arch} index={i} />
        ))}
      </div>

      <div className="ea-actions">
        <button
          type="button"
          onClick={() => window.print()}
          className="ea-action primary"
          aria-label="Export all three architectures as a PDF"
        >
          📄 Export as PDF (all 3)
        </button>
        <button
          type="button"
          onClick={() => openInMermaidLive(current)}
          className="ea-action"
          aria-label="Open current architecture in Mermaid Live Editor"
          title="Opens in mermaid.live — edit, render, export PNG/SVG"
        >
          ↗ Open current in Mermaid Live
        </button>
        <button
          type="button"
          onClick={copyAllAsMarkdown}
          className="ea-action"
          aria-label="Copy all 3 architectures as markdown"
          title="Copies markdown with one ```mermaid fence per architecture"
        >
          {copied === -1 ? '✓ Copied all 3' : 'Copy all 3 as Markdown'}
        </button>
        <button type="button" onClick={onReset} className="ea-action">
          ↻ Start over
        </button>
      </div>

      <div className="ea-footer-attribution">
        Generated by EA Architecture Explorer · sajivfrancis.com ·{' '}
        {new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })}
      </div>
    </div>
  );
}

function ArchitectureSection({
  arch,
  index,
}: {
  arch: Architecture;
  index: number;
}) {
  return (
    <section className="ea-arch-section">
      <div className="ea-arch-header">
        <h2 className="ea-arch-name">{arch.name}</h2>
        <span className="ea-arch-pill">{TAB_LABELS[index]}</span>
      </div>

      {arch.executiveSummary && (
        <p className="ea-arch-summary">{arch.executiveSummary}</p>
      )}

      {arch.rationale && (
        <p className="ea-arch-rationale">{arch.rationale}</p>
      )}

      <h3 className="ea-subhead">Architecture diagram</h3>
      <MermaidDiagram arch={arch} />

      <h3 className="ea-subhead">Integration patterns</h3>
      <IntegrationTable arch={arch} />

      <h3 className="ea-subhead">Tradeoffs</h3>
      <Tradeoffs arch={arch} />

      <h3 className="ea-subhead">Implementation roadmap</h3>
      <Roadmap arch={arch} />
    </section>
  );
}

function MermaidDiagram({ arch }: { arch: Architecture }) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;

    async function render() {
      try {
        const { default: mermaid } = await import('mermaid');
        const isDark =
          document.documentElement.dataset.theme === 'dark';
        mermaid.initialize({
          startOnLoad: false,
          theme: isDark ? 'dark' : 'default',
          securityLevel: 'strict',
          fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
        });
        const source = architectureToMermaid(arch);
        const id = 'ea-mermaid-' + Math.random().toString(36).slice(2, 10);
        const { svg } = await mermaid.render(id, source);
        if (!cancelled && ref.current) {
          ref.current.innerHTML = svg;
        }
      } catch (err) {
        // Mermaid render can fail on unusual node names; fail soft and
        // keep the integration table + roadmap as the load-bearing content.
        console.warn('Mermaid render failed:', err);
        if (!cancelled && ref.current) {
          ref.current.innerHTML =
            '<div style="padding:1rem;color:var(--color-fg-muted);font-size:0.875rem;text-align:center">Diagram could not be rendered. The integration patterns table below shows the same flows.</div>';
        }
      }
    }

    render();
    return () => {
      cancelled = true;
    };
  }, [arch]);

  return <div ref={ref} className="ea-mermaid-diagram" aria-label="Architecture diagram" />;
}

function IntegrationTable({ arch }: { arch: Architecture }) {
  const nodeMap = new Map(arch.nodes?.map((n) => [n.id, n.vendor]) ?? []);
  return (
    <table className="ea-int-table">
      <thead>
        <tr>
          <th>From → To</th>
          <th>Pattern</th>
          <th>What flows</th>
        </tr>
      </thead>
      <tbody>
        {(arch.edges ?? []).map((edge, i) => (
          <tr key={i}>
            <td>
              {nodeMap.get(edge.from) ?? edge.from} →{' '}
              {nodeMap.get(edge.to) ?? edge.to}
            </td>
            <td>
              <span className="ea-int-pattern">{edge.label}</span>
            </td>
            <td>{edge.description ?? ''}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Tradeoffs({ arch }: { arch: Architecture }) {
  return (
    <div className="ea-tradeoffs">
      <div className="ea-tradeoff strengths">
        <h4>Strengths</h4>
        <ul>
          {(arch.strengths ?? []).map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ul>
      </div>
      <div className="ea-tradeoff">
        <h4>Considerations</h4>
        <ul>
          {(arch.considerations ?? []).map((c, i) => (
            <li key={i}>{c}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function Roadmap({ arch }: { arch: Architecture }) {
  const phases = arch.roadmap ?? [];
  if (phases.length === 0) return null;
  return (
    <div className="ea-roadmap">
      {phases.map((p, i) => (
        <div key={i} className="ea-roadmap-phase">
          <div className="ea-roadmap-phase-name">{p.phase}</div>
          <div className="ea-roadmap-phase-duration">{p.duration}</div>
          <ul>
            {p.items.map((item, j) => (
              <li key={j}>{item}</li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}
