import { useState } from 'react';
import type { Architecture, Industry, GenerateResult } from './types';
import { LAYERS } from './data';
import { architectureToMermaid } from './api';

const LAYER_ORDER = ['source', 'ot', 'erp', 'middleware', 'data', 'bi', 'ai'];
const TAB_LABELS = ['Primary', 'Alternate 1', 'Alternate 2'];

interface Props {
  result: GenerateResult;
  industry: Industry;
  onReset: () => void;
}

export function ResultsView({ result, industry, onReset }: Props) {
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied] = useState<number | null>(null);

  if (!result?.architectures?.length) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <p style={{ color: 'var(--color-fg-muted)' }}>
          The response couldn't be parsed. This is rare — try regenerating.
        </p>
        <button type="button" onClick={onReset} className="ea-action">
          Start over
        </button>
      </div>
    );
  }

  const archs = result.architectures;
  const current = archs[activeTab];

  async function copyMermaid(arch: Architecture, idx: number) {
    const src = architectureToMermaid(arch);
    try {
      await navigator.clipboard.writeText(src);
      setCopied(idx);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      // Fallback: show in a prompt for manual copy
      window.prompt('Copy this Mermaid source:', src);
    }
  }

  return (
    <div>
      <div className="ea-industry-banner">
        <span className="ea-industry-banner-icon" aria-hidden="true">
          {industry.icon}
        </span>
        <div style={{ flex: 1 }}>
          <div className="ea-industry-banner-title">
            {industry.label} reference architecture
          </div>
          <div className="ea-industry-banner-sub">
            Three options below — primary plus two alternates. Switch tabs on
            screen, or print/save the page to capture all three as a PDF.
          </div>
        </div>
        <button type="button" onClick={onReset} className="ea-action">
          ← New session
        </button>
      </div>

      {/* On-screen tabs (hidden in print) */}
      <div className="ea-results-tabs" role="tablist">
        {archs.map((arch, i) => (
          <button
            key={i}
            type="button"
            role="tab"
            aria-selected={activeTab === i}
            onClick={() => setActiveTab(i)}
            className={`ea-results-tab${activeTab === i ? ' active' : ''}`}
          >
            {TAB_LABELS[i]}
            {arch.name && (
              <span className="ea-results-tab-name">{arch.name}</span>
            )}
          </button>
        ))}
      </div>

      {/* On-screen: render only the active tab */}
      <div className="ea-screen-only">
        <ArchitectureSection arch={current} index={activeTab} />
      </div>

      {/* Print-only: render ALL three architectures with page breaks */}
      <div className="ea-print-only">
        {archs.map((arch, i) => (
          <ArchitectureSection key={i} arch={arch} index={i} />
        ))}
      </div>

      <div className="ea-actions">
        <button
          type="button"
          onClick={() => window.print()}
          className="ea-action primary"
          aria-label="Export all three architectures as a PDF"
        >
          📄 Export as PDF (all 3)
        </button>
        <button
          type="button"
          onClick={() => copyMermaid(current, activeTab)}
          className="ea-action"
          aria-label="Copy current architecture as Mermaid source"
        >
          {copied === activeTab ? '✓ Copied' : 'Copy as Mermaid'}
        </button>
        <button type="button" onClick={onReset} className="ea-action">
          ↻ Start over
        </button>
      </div>

      <div className="ea-footer-attribution">
        Generated by EA Architecture Explorer · sajivfrancis.com ·{' '}
        {new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })}
      </div>
    </div>
  );
}

function ArchitectureSection({
  arch,
  index,
}: {
  arch: Architecture;
  index: number;
}) {
  return (
    <section className="ea-arch-section">
      <div className="ea-arch-header">
        <h2 className="ea-arch-name">{arch.name}</h2>
        <span className="ea-arch-pill">{TAB_LABELS[index]}</span>
      </div>

      {arch.executiveSummary && (
        <p className="ea-arch-summary">{arch.executiveSummary}</p>
      )}

      {arch.rationale && (
        <p className="ea-arch-rationale">{arch.rationale}</p>
      )}

      <h3 className="ea-subhead">Architecture diagram</h3>
      <ArchDiagram arch={arch} />

      <h3 className="ea-subhead">Integration patterns</h3>
      <IntegrationTable arch={arch} />

      <h3 className="ea-subhead">Tradeoffs</h3>
      <Tradeoffs arch={arch} />

      <h3 className="ea-subhead">Implementation roadmap</h3>
      <Roadmap arch={arch} />
    </section>
  );
}

function ArchDiagram({ arch }: { arch: Architecture }) {
  const nodesByLayer: Record<string, typeof arch.nodes> = {};
  for (const node of arch.nodes ?? []) {
    if (!nodesByLayer[node.layer]) nodesByLayer[node.layer] = [];
    nodesByLayer[node.layer]!.push(node);
  }
  const activeLayers = LAYER_ORDER.filter(
    (l) => (nodesByLayer[l]?.length ?? 0) > 0,
  );

  // Map layerId → first edge label going OUT of that layer
  const edgeLabels: Record<string, string> = {};
  for (const edge of arch.edges ?? []) {
    const fromNode = arch.nodes?.find((n) => n.id === edge.from);
    if (fromNode && !edgeLabels[fromNode.layer]) {
      edgeLabels[fromNode.layer] = edge.label;
    }
  }

  return (
    <div className="ea-diagram">
      {activeLayers.map((layerId, idx) => {
        const layer = LAYERS.find((l) => l.id === layerId)!;
        const nodes = nodesByLayer[layerId]!;
        const isLast = idx === activeLayers.length - 1;
        return (
          <div key={layerId}>
            <div className="ea-diagram-row">
              <div className="ea-diagram-layer">
                {layer.icon} {layer.label}
              </div>
              <div className="ea-diagram-divider" aria-hidden="true" />
              <div className="ea-diagram-vendors">
                {nodes.map((node) => (
                  <span key={node.id} className="ea-diagram-chip">
                    {node.vendor}
                  </span>
                ))}
              </div>
            </div>
            {!isLast && (
              <div className="ea-diagram-flow" aria-hidden="true">
                <div className="ea-diagram-arrow-line" />
                <div className="ea-diagram-flow-label">
                  <div className="ea-diagram-arrow-line" />
                  {edgeLabels[layerId] && (
                    <span className="ea-diagram-flow-pill">
                      {edgeLabels[layerId]}
                    </span>
                  )}
                </div>
                <div className="ea-diagram-arrow" />
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

function IntegrationTable({ arch }: { arch: Architecture }) {
  const nodeMap = new Map(arch.nodes?.map((n) => [n.id, n.vendor]) ?? []);
  return (
    <table className="ea-int-table">
      <thead>
        <tr>
          <th>From → To</th>
          <th>Pattern</th>
          <th>What flows</th>
        </tr>
      </thead>
      <tbody>
        {(arch.edges ?? []).map((edge, i) => (
          <tr key={i}>
            <td>
              {nodeMap.get(edge.from) ?? edge.from} →{' '}
              {nodeMap.get(edge.to) ?? edge.to}
            </td>
            <td>
              <span className="ea-int-pattern">{edge.label}</span>
            </td>
            <td>{edge.description ?? ''}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Tradeoffs({ arch }: { arch: Architecture }) {
  return (
    <div className="ea-tradeoffs">
      <div className="ea-tradeoff strengths">
        <h4>Strengths</h4>
        <ul>
          {(arch.strengths ?? []).map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ul>
      </div>
      <div className="ea-tradeoff">
        <h4>Considerations</h4>
        <ul>
          {(arch.considerations ?? []).map((c, i) => (
            <li key={i}>{c}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function Roadmap({ arch }: { arch: Architecture }) {
  const phases = arch.roadmap ?? [];
  if (phases.length === 0) return null;
  return (
    <div className="ea-roadmap">
      {phases.map((p, i) => (
        <div key={i} className="ea-roadmap-phase">
          <div className="ea-roadmap-phase-name">{p.phase}</div>
          <div className="ea-roadmap-phase-duration">{p.duration}</div>
          <ul>
            {p.items.map((item, j) => (
              <li key={j}>{item}</li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}
